on: push
name: 'Trigger: Push'
jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Run Shellcheck
      uses: ./
      with:
        ignore: ignore
